source/routes/admin.php
<?php
Route::get('/logout', function () {
    \Illuminate\Support\Facades\Auth::logout();
    return redirect()->route('login');
})->name('logout');

Route::get('switch/{locale}', 'LanguageController@getSwitchLang')->name('get_switch_lang');

Route::group(['middleware' => 'admin'], function () {

    Route::get('/admin','Admin\DashBoardController@index')->name('admin.dashboard');
    /*User*/
    
    Route::resource('/admin/user', 'Admin\UserController', ['as' => 'admin']);
    Route::get('/admin/user/profile/show', 'Admin\UserController@getProfile')->name('admin.user.get_profile');
    Route::put('/admin/user/profile/show', 'Admin\UserController@updateProfile');
    Route::patch('/admin/user/profile/show', 'Admin\UserController@updatePassword');
    Route::get('/admin/user/deleted/list', 'Admin\UserController@getDeletedUser')->name('admin.user.get_deleted');
    Route::put('/admin/user/deleted/{id}', 'Admin\UserController@restore')->name('admin.user.restore');
    Route::get('/admin/search/user', 'Admin\UserController@search')->name('admin.user.search');
    Route::get('/admin/user/add/show', 'Admin\UserController@getAddUser')->name('admin.user.add');


    /*Role*/
    Route::resource('role', 'Admin\RoleController', ['as' => 'admin']);

    /*Post*/
    Route::resource('/admin/post', 'Admin\PostController', ['as' => 'admin']);
    Route::put('/admin/publish/post/{id}', 'Admin\PostController@postPublishPost')->name('admin.post.publish');
    Route::patch('/admin/publish/post/{id}', 'Admin\PostController@postUnPublishPost')->name('admin.post.unpublish');
    Route::get('/admin/search/post', 'Admin\PostController@search')->name('admin.post.search');
    Route::get('/admin/post/deleted/list', 'Admin\PostController@getDeletedPost')->name('admin.post.get_deleted');
    Route::put('/admin/post/deleted/{id}', 'Admin\PostController@restore')->name('admin.post.restore');
    Route::post('/admin/post/position', 'Admin\PostController@postPosition')->name('admin.post.post_position');
    /*Image*/
    Route::get('/admin/image/{model}/{id}', 'Admin\MultiImageController@getListImage')->name('admin.image.list');
    Route::post('/admin/image/{model}/{id}', 'Admin\MultiImageController@postUploadImage')->name('admin.image.upload');
    Route::put('/admin/image/{model}/{id}', 'Admin\MultiImageController@putChangePosition')->name('admin.image.position');
    /*Product*/
    Route::resource('/admin/product', 'Admin\ProductController', ['as' => 'admin']);
    Route::get('/admin/search/product', 'Admin\ProductController@search')->name('admin.product.search');
    Route::get('/admin/product/deleted/list', 'Admin\ProductController@getDeletedProduct')->name('admin.product.get_deleted');
    Route::put('/admin/product/deleted/{id}', 'Admin\ProductController@restore')->name('admin.product.restore');
    Route::post('/admin/product/position', 'Admin\ProductController@productPosition')->name('admin.product.product_position');
});

Route::get('/tst', 'Admin\CategoryController@getTest');
require_once 'NamAdmin.php';
require_once 'NguyenAdmin.php';
require_once 'NguyenClient.php';

source/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
// Auth::routes();
require_once 'admin.php';
require_once 'quang.php';
require_once 'client.php'; //Nguyen + Nam task

source/app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    use Notifiable;

    use SoftDeletes;

    const PAGINATE = 10;
    const SYSTEM_ADMIN_ROLE = 1;

    const ACTIVED = 1;
    const UNACTIVE = 0;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password', 'first_name', 'last_name', 'phone', 'role_id', 'avatar','department_id','regency_id',
    ];

    protected $dates = ['deleted_at'];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function Department(){
        return $this->belongsTo(Department::class);
    }
    public function role()
    {
        return $this->belongsTo(Role::class)->withTrashed();
    }

    public static function getListUsers()
    {
        return self::with('role')->where('role_id', '<>', self::SYSTEM_ADMIN_ROLE)->paginate(self::PAGINATE);
    }

    public static function getDeletedUsers()
    {
        return self::with('role')->onlyTrashed()->paginate(self::PAGINATE);
    }

    public static function getUserFromID($id)
    {
        return $user = self::findOrFail($id);
    }

    public static function getDeletedUserFromID($id)
    {
        return self::withTrashed()->findOrFail($id);
    }

    public static function search($keyword)
    {
        $keyword = !empty($keyword) ? $keyword : '';

        $users = self::where(function ($query) use ($keyword) {
           $query->where('first_name', 'like', '%'.$keyword.'%')
               ->orWhere('last_name', 'like', '%'.$keyword.'%')
               ->orWhere('email', 'like', '%'.$keyword.'%')
               ->orWhere('username', 'like', '%'.$keyword.'%')
               ->orWhere('phone', 'like', '%'.$keyword.'%');
        })->where('role_id', '<>', self::SYSTEM_ADMIN_ROLE);
        
        return $users->paginate(self::PAGINATE);

    }

}

source/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\AddUserRequest;
use App\Http\Requests\UpdatePasswordRequest;
use App\Http\Requests\UpdateProfileRequest;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    public $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     *
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users =  $this->user->getListUsers();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddUserRequest $request)
    {
        $code = md5($request->username.time());
        $code = substr($code, 0, 12);
        $password = bcrypt($code);
        $request->request->add(['phone' => $code, 'password' => $password]);
        User::create($request->all());
        return redirect()->route('admin.user.index')->with('success', [
            'type' => 'success', 'message' => trans('admin.message.user.create'), 'title' => 'Message'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->user->getUserFromID($id);
        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->user->getUserFromID($id);
        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = $this->user->getUserFromID($id);
       
        $user->update($request->all());
        $user->password = bcrypt($request->password);
        $user->update();
        return redirect()->route('admin.user.index')->with('success',
            ['type' => 'success', 'message' => trans('admin.message.user.edit'), 'title' => 'Message']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user->getUserFromID($id)->delete();

        return redirect()->route('admin.user.index')->with('success',
            ['type' => 'success', 'message' => trans('admin.message.user.delete'), 'title' => 'Message']);
    }

    public function getDeletedUser()
    {
        $users = $this->user->getDeletedUsers();
        return view('admin.user.restore', compact('users'));
    }

    public function restore($id)
    {
        $this->user->getDeletedUserFromID($id)->restore();
        return redirect()->route('admin.user.index')->with('success',
            ['type' => 'success', 'message' => trans('admin.message.user.restore'), 'title' => 'Message']);
    }

    public function search(Request $request)
    {
        $users = $this->user->search($request->keyword);
        return view('admin.user.search', compact('users', 'request'));
    }

    public function getProfile()
    {
        $user = Auth::user();
        return view('admin.user.profile', compact('user'));
    }

    public function updateProfile(UpdateProfileRequest $request)
    {
        $user = User::getUserFromID(Auth::user()->id);

        if($request->hasFile('image_file')){
            $img = Image::make($_FILES['image_file']['tmp_name']);
            $newName = md5($_FILES['image_file']['tmp_name'].time());
            $img->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save(public_path('assets/images/'.$newName.'.'.$request->image_file->getClientOriginalExtension()));
            $request->request->add(['avatar' => $newName.'.'.$request->image_file->getClientOriginalExtension()]);
        }

        $user->update($request->all());

        return redirect()->back()->with('success', [
            'type' => 'success', 'message' => trans('admin.message.user.update_profile'), 'title' => 'Message'
        ]);
    }

    public function updatePassword(UpdatePasswordRequest $request)
    {   
        $user = User::getUserFromID(Auth::user()->id);
        $user->password = bcrypt($request->password);
        $user->save();
        return redirect()->back()->with('success', [
            'type' => 'success', 'message' => trans('admin.message.user.update_password'), 'title' => 'Message'
        ]);
    }

    public function getAddUser()
    {
        return view('admin.user.create');
    }

}

source/app/Http/Controllers/Client/UserController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App;
use DB;
class UserController extends Controller
{
    //
    public $list = 15;
    public $limit = 5;
    public function loadStaffBar(){
        $user = DB::table('users')->limit(5)->get();
        return $user;
    }

    public function getStaffActive(Request $request) {
      
        $department_id = $request->department_id;
        $last_staff = $request->last_staff;
        $staff = App\User::join('departments','users.department_id','=','departments.id')->where('departments.id',$department_id)->where('users.id','>',$last_staff)->select('users.*')->limit($this->list)->get();   
        return ($staff);
    }
}

source/resources/views/admin/user/create.blade.php
@extends('layouts.admin.master')
@section('title', trans('admin.title.user.add'))
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <form id="user" action="{{ route('admin.user.store') }}" method="post" enctype="multipart/form-data">
                    <div class="box">
                        <!-- /.box-header -->
                        <div class="box-body">
                            {{ csrf_field() }}
                            <div class="form-group @if($errors->has('first_name')) has-error @endif">
                                <label>{{ trans('admin.label.user.first_name') }} <span class="text-danger">*</span></label>
                                <input type="text" name="first_name" class="form-control" placeholder="{{ trans('admin.place.user.first_name') }}">
                                @if($errors->has('first_name'))
                                    <p class="text-danger">{{ $errors->first('first_name') }}</p>
                                @endif
                            </div>
                            <div class="form-group @if($errors->has('last_name')) has-error @endif">
                                <label>{{ trans('admin.label.user.last_name') }} <span class="text-danger">*</span></label>
                                <input type="text" name="last_name" class="form-control" placeholder="{{ trans('admin.place.user.last_name') }}">
                                @if($errors->has('last_name'))
                                    <p class="text-danger">{{ $errors->first('last_name') }}</p>
                                @endif
                            </div>
                            <div class="form-group @if($errors->has('username')) has-error @endif">
                                <label>{{ trans('admin.label.user.username') }} <span class="text-danger">*</span></label>
                                <input type="text" name="username" class="form-control" placeholder="{{ trans('admin.place.user.username') }}">
                                @if($errors->has('username'))
                                    <p class="text-danger">{{ $errors->first('username') }}</p>
                                @endif
                            </div>
                            <div class="form-group @if($errors->has('email')) has-error @endif">
                                <label>{{ trans('admin.label.user.email') }} <span class="text-danger">*</span></label>
                                <input type="text" name="email" class="form-control" placeholder="{{ trans('admin.place.user.email') }}">
                                @if($errors->has('email'))
                                    <p class="text-danger">{{ $errors->first('email') }}</p>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="department">{{ trans('admin.label.user.department') }} </label>
                                <select class="form-control" name="role_id">
                                    @foreach(\App\Department::all() as $value)
                                        <option value="{{ $value->id }}">{{ $value->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group @if($errors->has('role_id')) has-error @endif">
                                <label>{{ trans('admin.label.user.role') }} <span class="text-danger">*</span></label>
                                <select class="form-control" name="role_id">
                                    @foreach(\App\Role::where('id', '<>', 1)->get() as $role)
                                        <option value="{{ $role->id }}">{{ $role->name }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('role_id'))
                                    <p class="text-danger">{{ $errors->first('role_id') }}</p>
                                @endif
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">{{ trans('admin.button.create') }}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <script>
        $("#user").validate({
            errorClass: 'text-danger',
            errorElement: 'p',
            highlight: function (element) {
                $(element).parents('div.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).parents('div.form-group').removeClass('has-error');
            },
            ignore: [],
            rules: {
                first_name:{
                    required: true,
                    maxlength: 32
                },
                last_name: {
                    required: true,
                    maxlength: 32
                },
                username: {
                    required: true,
                    maxlength: 32
                },
                email: {
                    required: true,
                    email: true,
                    maxlength: 128
                },
                role_id :{
                    required: true
                }
            }
        });
    </script>
@endsection

source/resources/views/admin/user/edit.blade.php
@extends('layouts.admin.master')
@section('title', trans('admin.title.user.edit').": ".$user->email)
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        @include('admin.user.search_form')
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <form role="form" action="{{ route('admin.user.update', $user) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('put') }}
                            <div class="form-group">
                                <label for="first_name">{{ trans('admin.label.user.first_name') }}</label>
                                <input value="{{ $user->first_name }}" type="text" name="first_name" class="form-control" placeholder="{{ trans('admin.place.user.firstname') }}">
                            </div>
                            <div class="form-group">
                                <label  for="last_name">{{ trans('admin.label.user.last_name') }}</label>
                                <input value="{{ $user->last_name }}" type="text" name="last_name" class="form-control" placeholder="{{ trans('admin.place.user.lastname') }}">
                            </div>
                            <div class="form-group">
                                <label  for="password">{{ trans('admin.label.user.password') }}</label>
                                <input  type="text" name="password" class="form-control" placeholder="{{ trans('admin.place.user.password') }}">
                            </div>
                            <div class="form-group">
                                <label for="role">{{ trans('admin.label.user.role') }} </label>
                                <select class="form-control" name="role_id">
                                    @foreach(\App\Role::where('id', '<>', \App\Role::SYSTEM_ADMIN_ROLE)->get() as $value)
                                        <option @if($value->id == $user->role->id) selected @endif value="{{ $value->id }}">{{ $value->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="department">{{ trans('admin.label.user.department') }} </label>
                                <select class="form-control" name="department_id">
                                    @foreach(\App\Department::all() as $value)
                                        <option @if($value->id == $user->department_id) selected @endif value="{{ $value->id }}">{{ $value->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">{{ trans('admin.button.update') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

source/resources/views/admin/user/index.blade.php
@extends('layouts.admin.master')
@section('title', trans('admin.title.user.index'))
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        @include('admin.user.search_form')
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-hover">
                            <tbody><tr>
                                <th>{{ trans('admin.table.id') }}</th>
                                <th>{{ trans('admin.table.full_name') }}</th>
                                <th>{{ trans('admin.table.username') }}</th>
                                <th>{{ trans('admin.table.email') }}</th>
                                <th>{{ trans('admin.table.created_at') }}</th>
                                <th>{{ trans('admin.table.role') }}</th>
                                <th>{{ trans('admin.table.department') }}</th>
                                <th>{{ trans('admin.table.function') }}</th>
                            </tr>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->first_name.' '.$user->last_name }}</td>
                                    <td><a href="{{ route('admin.user.show', $user) }}">{{ $user->username }}</a></td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ \Carbon\Carbon::createFromTimestamp(strtotime($user->created_at))->format('d-m-Y') }}</td>
                                    <td><a href="{{ route('admin.role.show', $user->role) }}">{{ $user->role->name }}</a></td>
                                    <td>
                                        
                                        @if($user->department_id)
                                           {{$user->department->name}}
                                        @endif
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                                <span class="caret"></span> {{ trans('admin.button.function') }}
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="{{ route('admin.user.edit', $user) }}">{{ trans('admin.button.edit') }}</a>
                                                </li>
                                                <li>
                                                    <form class="form_delete_{{ $user->id }}" action="{{ route('admin.user.destroy', $user) }}" method="post">
                                                        {{ csrf_field() }}
                                                        {{ method_field('delete') }}
                                                    </form>
                                                    <a type="button" target-id="{{ $user->id }}" href="javascript:void(0)" class="delete">{{ trans('admin.button.delete') }}</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="box-footer clearfix">
                        {{ $users->render() }}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('script_extra')
    <script src="{{ asset('js/delete_confirm.js') }}"></script>
    <script>
        $(document).ready(function () {
            deleteWithConfirm('{{ trans('admin.button.delete_confirm') }}');
        });
    </script>
@endsection

source/resources/views/admin/user/search.blade.php
@extends('layouts.admin.master')
@section('title', trans('admin.title.user.search'))
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        @include('admin.user.search_form')
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tbody><tr>
                                <th>{{ trans('admin.table.id') }}</th>
                                <th>{{ trans('admin.table.full_name') }}</th>
                                <th>{{ trans('admin.table.username') }}</th>
                                <th>{{ trans('admin.table.email') }}</th>
                                <th>{{ trans('admin.table.created_at') }}</th>
                                <th>{{ trans('admin.table.role') }}</th>
                                <th>{{ trans('admin.table.status') }}</th>
                                <th>{{ trans('admin.table.edit') }}</th>
                                <th>{{ trans('admin.table.delete') }}</th>
                            </tr>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->first_name.' '.$user->last_name }}</td>
                                    <td><a href="{{ route('admin.user.show', $user) }}">{{ $user->username }}</a></td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ \Carbon\Carbon::createFromTimestamp(strtotime($user->created_at))->format('d-m-Y') }}</td>
                                    <td><a href="{{ route('admin.role.show', $user->role) }}">{{ $user->role->name }}</a></td>
                                    <td>
                                        @if($user->status == \App\User::ACTIVED)
                                            <span class="label label-success">{{ trans('admin.status.active') }}</span>
                                        @else
                                            <span class="label label-danger">{{ trans('admin.status.deactive') }}</span>
                                        @endif
                                    </td>
                                    <td><a href="{{ route('admin.user.edit', $user) }}" class="btn btn-warning">{{ trans('admin.button.edit') }}</a></td>
                                    <td>
                                        <form action="{{ route('admin.user.destroy', $user) }}" method="post">
                                            {{ csrf_field() }}
                                            {{ method_field('delete') }}
                                            <button type="submit" class="btn btn-danger delete">{{ trans('admin.button.delete') }}</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="box-footer clearfix">
                        {{ $users->appends(['keyword' => $request->keyword])->render() }}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

source/resources/views/admin/user/search_form.blade.php
<div class="box-tools">
    <form action="{{ route('admin.user.search') }}" method="get">
        <div class="input-group input-group-sm" style="width: 150px;">
            <input value="@if(isset($request)){{ $request->keyword }}@endif" type="text" name="keyword" class="form-control pull-right" placeholder="{{ trans('admin.place.user.search') }}">

            <div class="input-group-btn">
                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>
</div>

source/resources/views/admin/user/show.blade.php
@extends('layouts.admin.master')
@section('title', trans('admin.title.user.show').": ".$user->email)
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <p>{{ trans('admin.label.user.fullname') }} : {{ $user->first_name.' '.$user->last_name }}</p>
                        <p>{{ trans('admin.label.user.username') }} : {{ $user->username }}</p>
                        <p>{{ trans('admin.label.user.email') }} : {{ $user->email }}</p>
                        <p>{{ trans('admin.label.user.phone') }} : {{ $user->phone }}</p>
                        <p>{{ trans('admin.label.user.address') }} : {{ $user->address }}</p>
                        <p>{{ trans('admin.label.user.role') }} : {{ $user->role->name }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection